# Generated by Django 5.2 on 2025-05-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0068_merge_20241216_1552"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohortuser",
            name="educational_status_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
